const express = require('express')
const app = express()
let { validateAttendance } = require(`../middlewares/attendance-validation`)
app.use(express.json())
const attendanceController = require(`../controller/attendance.controller`)
const { authorize } = require(`../controller/auth.controller`)
app.post("/", [validateAttendance], [authorize], attendanceController.addAttendance)
app.get("/history/:user_id", [authorize], attendanceController.getAttendanceById)
app.get("/summary/:user_id", [authorize], attendanceController.getMonthlyAttendanceSummary)
app.post("/analysis", [authorize], attendanceController.analyzeAttendance)
module.exports = app